# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-with-prod-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache dependencies
      id: cache-npm
      uses: actions/cache@v3
      with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ runner.arch }}-npm-v3-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies (cache miss)
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm ci

    - name: Install dependencies (cache hit)
      if: steps.cache-npm.outputs.cache-hit == 'true'
      run: npm run postinstall
      
    - name: Build production app
      env:
        NO_INSTALLER: true
      run: npm run build:electron:${{ runner.os }}:${{ runner.arch }}

    - name: Run Tests
      env:
        EXECUTABLE_PATH: github-actions-production
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm test
